# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://sigbit.org" # the url of your github pages

# site information used in page title, meta data etc.
title: "SIGBIT"
description: Special Interest Group on Blockchain Innovations and Technologies

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
home-title: 2022 SIGBIT Workshop on Web3 Technologies and Applications
home-subtitle: false
home-time-location: "December 11, 2022 | Copenhagen, Denmark"  # change to false to hide
author-image: sigbit.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

# internal page menu
nav-menu:
- text: CFP
  permalink: cfp
- text: Committee
  permalink: committee

# external menu - always shown
nav-menu-external:
- text: SIGBIT
  url: https://sigbit.org/

# use false to turn off any social media links
twitter: https://twitter.com/SIGBIT_AIS
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: "mailto:shaokun.fan@oregonstate.edu?subject=2022 SIGBIT Workshop Inquiry"
eth: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-L6N7PNG6BV

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
